repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [ --fix ]

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.39.2
    hooks:
      - id: eslint
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts, *.tsx
        types: [file]
        additional_dependencies:
          - eslint@9.39.2
          - eslint-plugin-react@7.37.5
          - eslint-plugin-react-hooks@7.0.1
          - eslint-plugin-jsx-a11y@6.10.2
          - "@typescript-eslint/eslint-plugin@8.53.0"
          - "@typescript-eslint/parser@8.53.0"
          - eslint-config-prettier@10.1.8
          - eslint-plugin-react-refresh@0.4.26

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [css, javascript, jsx, ts, tsx, json, markdown]
        additional_dependencies:
          - prettier@3.8.0
